### ISSUE TITLE
Edit paper

### ISSUE THREAD

**Issue by pllim** [pllim/ginga-poster-adass2018#15]
Follow up of #9 and #14

**Comment by ejeschke** [comment]
We need to change the name to comply with the naming scheme for the poster numbering scheme used by ADASS. Did you get a number and letter for the poster? (Usually the letter is "P").

**Comment by ejeschke** [comment]
> @ejeschke , is this the number (P11.3)? http://adass2018.umd.edu/abstracts/P11.3.html

Yes!  So our number is 11.3.  Can you look up the naming conventions (should be under "instructions for authors" or some such).  I believe it will be something like `P11_3_*.*` for all files and figures.

**Comment by pllim** [comment]
Yes, I downloaded the 21-page instructions. Will have to read it...

**Comment by pllim** [comment]
Thanks!
