### ISSUE TITLE
Poster dimension

### ISSUE THREAD

**Issue by pllim** [pllim/ginga-poster-adass2018#19]
@ejeschke , I just saw that, "The maximum size for posters is 45 inches wide x 45 inches long." Are we in trouble? I already sent it for printing.

http://adass2018.umd.edu/instructions.html

**Comment by ejeschke** [comment]
Hmm, that seems smaller than in past years, where I've used that template without any issue.  Here is what Google says for the size:

Size	Width x Height (mm)	Width x Height (in)
B0	1000 x 1414 mm	39.4 x 55.7 in
B1     707 x 1000 mm      27.8 x 39.4 in

So width wise it is fine.  I suspect the height will not be an issue, unless they are stacking posters vertically (never seen that).

But we could make a backup poster by shrinking to B1 size just in case.  I can bring it in a tube and discard it if there is no problem putting up yours.

**Comment by ejeschke** [comment]
Shall I do that?

**Comment by pllim** [comment]
>  can bring it in a tube

Are you sure? It is not fun to carry for such a long flight. :scream:

**Comment by pllim** [comment]
I can also submit it for paper printing too and much shorter commute. Shall I do it instead?

**Comment by pllim** [comment]
@ejeschke , please don't worry about it. Now that you provided an alternate size, I'll go head and get the paper one printed on my end. Thanks!

**Comment by pllim** [comment]
(But feel free to take the paper version home with you if you want to keep it after.) :smile:

**Comment by ejeschke** [comment]
Ok, I will leave that for you.  You can probably just load the current poster and print it to a B1 size paper, checking the box for "shrink to fit".  I think the aspect ratios are all the same for B0, B1, B2, ...

**Comment by pllim** [comment]
@ejeschke , I got the paper one ready to go. FYI.
