### ISSUE TITLE
Potential broken link in poster

### ISSUE THREAD

**Issue by ejeschke** [pllim/ginga-poster-adass2018#22]
@pllim, I just realized that the link that we have in the poster to the plugin developers page is probably broken, since it refers to the page before the dev manual was split off from the user manual.

Not too late to update it in the paper, but we may need to pin a little correction stub on to the poster.

**Comment by ejeschke** [comment]
Ah, reviewing the site, I think the default is the last stable version right?  I was hoping to release 2.7.2 this week.

**Comment by pllim** [comment]
@ejeschke , can you please be specific on which is the problematic link? I thought I fixed it before printing.

**Comment by ejeschke** [comment]
Oops, my repo was stale!  Pulled your changes and now I see it is a bit.ly link.

**Comment by ejeschke** [comment]
Sorry, my mistake!

**Comment by pllim** [comment]
@ejeschke , does the `bit.ly` link work for you?
