### ISSUE TITLE
Check out different printing services

### ISSUE THREAD

**Issue by pllim** [pllim/ginga-poster-adass2018#5]
https://postersmith.com ($100-ish, 2-day shipping)

https://www.spoonflower.com ($30-ish, 6-7 days)

**Comment by pllim** [comment]
Oh, dear. Whichever service it is, I would need expedited one at this rate. :scream:

**Comment by ejeschke** [comment]
No worries.  If necessary we can do it the old-fashioned way with a poster tube.

Are you confirmed to go?

**Comment by pllim** [comment]
Let's hope this works... https://support.spoonflower.com/hc/en-us/articles/204266984-How-to-Create-a-Fabric-Poster-from-a-PowerPoint-or-PDF 🤞
