### ISSUE TITLE
Add paper subdirectory

### ISSUE THREAD

**Issue by ejeschke** [pllim/ginga-poster-adass2018#9]
I will make a PR to add a `paper` subdirectory that has the template for the paper.  We can iterate on that as well.  We only get 4 pages for a poster presentation.  And due to the format and restrictions on type size and so forth there is not a lot of room.  Figures need to be minimal.

**Comment by pllim** [comment]
Sounds good. Thanks!

**Comment by ejeschke** [comment]
I think we can maybe get it down to 2-3 figures tops.  We'll have to cut out some of the text (the poster will actually be longer!).  Unless they have changed the rules for the length of poster papers this year.

**Comment by pllim** [comment]
Fixed by #14
